version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "7080:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/log-volume/nginx:/var/log/nginx
    depends_on:
      - api
    links:
      - api

  api:
    restart: on-failure
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    expose:
      - "3000"
      - "28080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://ubuntu@db/trb_development
      TEST_DATABASE_URL: postgresql://ubuntu@db/trb_test
      PORT: 3000

  db:
    image: camptocamp/postgres:9.6
    volumes:
      - ./docker/data-volume/postgresql:/var/lib/postgresql/data
    ports:
      - 5456:5432
    environment:
      POSTGRES_USER: ubuntu
      POSTGRES_DB: trb_database
      POSTGRES_PASSWORD: ""

volumes:
  bundle_cache:
