version: 2
jobs:
  api:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
        environment:
          - RAILS_ENV: test
          - BUNDLE_PATH: ~/project/bundle
          - TEST_DATABASE_URL: postgresql://ubuntu@localhost/trb_test
      - image: circleci/postgres:9.6.3-alpine
        environment:
          - POSTGRES_USER: ubuntu
          - POSTGRES_PASSWORD: ""
          - POSTGRES_DB: trb_test

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Update VHOST
          command: |
            echo 'export VHOST="http://localhost:7080"' >> $BASH_ENV
      - restore_cache:
          key: bundler-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Dependencies
          command: bin/bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: bundler-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
      - run:
          name: Create DB
          command: bin/rails db:schema:load --trace
      - run:
          name: Run Tests
          command: COVERAGE=true bin/rails test
      - store_artifacts:
          path: coverage

workflows:
  version: 2
  build:
    jobs:
      - api
